# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Alice Nassor # the website title (if blank, full name will be used instead)
first_name: Alice
middle_name: 
last_name: Nassor
email: alice.nassor@ensta-paris.fr
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Welcome on my academic page !
#footer_text: >
#  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: fluid-structure interaction, boundary element method, finite elements

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 🌊

url: https://alnssr.github.io/ # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR



# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------


twitter_username: AliceNs_ # your Twitter handle
linkedin_username: www.linkedin.com/in/alice-nassor # your LinkedIn user name
scholar_userid: # your Google Scholar ID


theme: jekyll-theme-cayman
include: ["_pages", "_assets"]
